### ISSUE TITLE
Issue in input tag

### ISSUE THREAD

**Issue by ghost** [cluemediator/dynamic-input-fields-reactjs#1]
Hi. I have used this in my code and the repeater is working fine. Thank you for that.
But I am facing one issue, when I change the input tag's type to file and I upload an image then I am receiving the fakepath as shown in image. I am encountering this problem only in repeater. If I use an input tag with type "file", outside the repeater then I am receiving the correct path. 

![Screenshot 2020-11-25 at 15 07 47](https://user-images.githubusercontent.com/46704464/100214105-460b9800-2f31-11eb-9c81-9799d3859f14.png)

The fake path is the main issue because if I extract the file name and upload it to s3 then empty image is uploaded to s3. 
How can I upload a file in repeater? The thing which I am trying to do is shown in the screenshot. Your help will be appreciated.
![Screenshot 2020-11-25 at 12 25 31](https://user-images.githubusercontent.com/46704464/100214170-5ae82b80-2f31-11eb-996a-229c42a2dd44.png)

**Comment by cluemediator** [comment]
You have to read the file information from the `e.target.files[0]`. Look at the image upload demo for your reference.

[Image upload in ReactJS](https://www.cluemediator.com/image-upload-in-reactjs)

**Comment by kharban** [comment]
@user09876090 have you solve the issue with the image file in add more functionality?
